preset: laravel

disabled:
  - laravel_braces
  - laravel_phpdoc_alignment
  - laravel_phpdoc_order
  - laravel_phpdoc_separation
  - single_class_element_per_statement

# https://docs.styleci.io/standalone-php#risky
risky: false

finder:
  exclude:
    - "build"
    - "tests"
    - "vendor"
  name:
    - "*.php"
